package:
  name: scwidgets
  version: {{ GIT_DESCRIBE_TAG }}

source:
  path: ..

requirements:
  build:
    - python {{ python }}
  run:
    - python {{ python }}
    - scipp
    - ipywidgets

test:
  import:
    - scwidgets
    - scwidgets.converters
    - scwidgets.widgets
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - python -m pytest -v

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

about:
  home: https://github.com/scipp/scipp-widgets
  license: GPLv3
  summary: ipywidget wrappers for scipp
  description: ipywidget wrappers for scipp
  dev_url: https://github.com/scipp/scipp-widgets
  doc_url:
