package:
  name: scwidgets
  version: "1"

source:
  path: ..

requirements:
  build:
    - python {{ python }}
  run:
    - python {{ python }}
    - scipp
    - ipywidgets
    - matplotlib

test:
  import:
    - scwidgets
    - scwidgets.converters
    - scwidgets.widgets
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - python -m pytest -v

build:
  number: "1"

about:
  home: https://github.com/scipp/scipp-widgets
  license: GPLv3
  summary: ipywidget wrappers for scipp
  description: ipywidget wrappers for scipp
  dev_url: https://github.com/scipp/scipp-widgets
  doc_url:
